### ISSUE TITLE
Misc. bug: vulkan on 6900xt

### ISSUE THREAD

**Issue by Danik-droid** [ggml-org/llama.cpp#12147]
### Name and Version

Latest vulkan patches cause problems in koboldCPP for radeon 6900xt.

### Operating systems

Windows

### Which llama.cpp modules do you know to be affected?

llama-quantize

### Command line

```shell

```

### Problem description & steps to reproduce

I reported a problem with vulkan on the KoboldCPP project page, and was asked to report the problem here (newly released koboldcpp version with latest fixes for vulkan).

https://github.com/LostRuins/koboldcpp/issues/1398

As I wrote in the bug report on KoboldCPP, I have two cards GTX 1080ti and Radeon 6900xt. When the creator of Koboldcpp included the latest patches for vulkan, my radeon stopped working properly with vulkan.

I have tested various models (llama 3.1, nemo, mistral small 22/24b) and in none of them vulkan on radeon 6900xt works correctly anymore, either some random characters are generated from the very beginning, or the response loops very quickly and repeats some word.

### Relevant log output

```shell

```

**Comment by 0cc4m** [comment]
Try to reinstall your driver, the backend is still working fine on my AMD RX 6800 XT on Linux and Windows, so it's likely a problem on your side.

**Comment by 0cc4m** [comment]
Actually, no, there seems to be some issue with the llama 3.1 model you linked, at least. I'll look into it.

**Comment by Danik-droid** [comment]
Yes, in llama 3 it works ok. But in llama 3.1 models - it generates wrong immediately, or mistral nemo and small 22b/24b not (quickly falls into loops and repeats one word).

I reinstalled AMD drivers (with factory reset) it did not help. Vulkan on 1080ti works correctly. 

Vulkan on the previous version of the program works correctly all the time on AMD Radeon 6900xt, even when I run the model on both graphics cards.

**Comment by 0cc4m** [comment]
Yes, thank you for the report. I'll let you know once I found the culprit.

**Comment by LostRuins** [comment]
thanks for the help

**Comment by 0cc4m** [comment]
@Danik-droid @LostRuins It's hard for me to check, since I don't use Windows and this is Windows-specific, but I'm pretty sure this is the bug already reported in #10710 . It's related to the use of `unpack8()` in shader code, which is currently bugged in the AMD Windows driver. An AMD employee in the aforementioned issue has already confirmed they fixed it, so it should be working in the next AMD driver update. I expect this to be released within the next few days, as AMD is releasing their new RDNA4 GPUs.

**Comment by LostRuins** [comment]
reverting https://github.com/ggml-org/llama.cpp/pull/12015 will fix q8_0 for now
ref: https://github.com/ggml-org/llama.cpp/issues/10710#issuecomment-2697960026
while we wait for amd to fix their driver

**Comment by Danik-droid** [comment]
In the latest 'Adrenalin 25.3.1' drivers it's a bit better, for example models based on nemo started working, llama 3.1 8b running only on radeon works correctly, when it's divided into two cards it doesn't. LLama 3.1 MOE still doesn't work regardless of how they're running. Mistral small 22B/24B after a while start repeating one word and looping on it.

**Comment by 0cc4m** [comment]
Apparently it's not even fixed for RDNA, I don't know what's going on there.

**Comment by 0cc4m** [comment]
Yeah, we can do that, but we would have to provide separate precompiled shader binaries for each shader that uses this, one without and one with the workaround. This would bloat the binary, but I'm not sure to what extent.

**Comment by netrunnereve** [comment]
@masamaru-san so you're saying that it only fails with a vec2 unpack8, right? If you make this change does the q8_0 test pass?

```diff
--------------- ggml/src/ggml-vulkan/vulkan-shaders/mul_mm.comp ---------------
index a8fd93fd..f7dc074b 100644
@@ -336,8 +336,8 @@ void main() {
             const uint iqs = idx & 0x07;
 
             const float d = float(data_a_packed16[ib].d);
-            const i8vec2 v0 = unpack8(data_a_packed16[ib].qs[2*iqs]);
-            const i8vec2 v1 = unpack8(data_a_packed16[ib].qs[2*iqs + 1]);
+            const i8vec4 v0 = unpack8(int32_t(data_a_packed16[ib].qs[2*iqs]));
+            const i8vec4 v1 = unpack8(int32_t(data_a_packed16[ib].qs[2*iqs + 1]));
             const vec4 v = vec4(v0.x, v0.y, v1.x, v1.y) * d;
 
             buf_a[buf_idx    ] = FLOAT_TYPE(v.x);
```

**Comment by netrunnereve** [comment]
Yeah AMD really needs to fix their drivers. I'm more concerned about the fact that they haven't touched the Vulkan drivers since September 2023 as that likely means that they won't update the Windows Polaris/Vega driver *ever*.

**Comment by Danik-droid** [comment]
Q8 don't work, Other Quants with L (Q8_0 for embed and output weights) work without any problems.

**Comment by netrunnereve** [comment]
@Danik-droid this is really confusing as you've posted in several threads and on the Kobold repo as well. First of all can you confirm if this issue is due to DP4A or is it broken in my initial fix https://github.com/ggml-org/llama.cpp/commit/30c42ef5cbb2db756eff9aadc6b6c528ba68388d as well?

For DP4A @0cc4m seems to have taken care of this with https://github.com/ggml-org/llama.cpp/commit/92e3006bb69dfeb656ccf5c7c1c1efadb03c88c2. If the issue is with my original shader let me know and I'll look into it.

**Comment by Danik-droid** [comment]
Sorry for the confusion. The last fix in koboltcpp fixed the issue with Q8 not working and problems in other quants with context above 4k.

Now everything seems to be working, plus the speed is slightly better, 2-3 t/s.

The topic can be closed, thank you very much for your help.

**Comment by LostRuins** [comment]
Thanks for verifying. I guess it was indeed due to the broken D4PA which Occam has fixed.

**Comment by Danik-droid** [comment]
Hello again.

I tested more over the weekend and the problem is still there, but this time it is more subtle.

As I wrote earlier, I have two GPU cards Nvidia 1080ti and AMD radeon 6900xt. With the current fixes, each of these cards works fine separately (the generated text makes sense, no driver instability). The problem starts when they start working together (when I load the model on both cards), every now and then - much less often than before, the AMD driver resets (occasionally hanging the system - if it is the main GPU in the system).

I would like to point out that I have reinstalled the drivers, and on the earlier version of koboltcpp 1.65.2 (without some fixes it works ok - although slower).

I tried to get to a situation where the problem can be caused and it seems to have worked: the problem occurs more often when both cards are used (memory) - for example: if the AMD card is used 90% and the Nvidia card only 10%, then the instability of the AMD driver occurs rarely. But if the Nvidia card is used more (higher quants), then the instability occurs more and more often. For example, for the mistral small 24B (Q5/Q6), the problem occurs very often - besides, interestingly, above about 12k context, nonsense is generated (some character in infinity, usually #) - only when using two cards at once - cards on Vulkan alone are able to generate these approx. 12k without any problems..

The driver error occurs when trying to generate (not process), or when trying to load models - less frequently.

I was going to buy another card from AMD... But I held back... There are always some problems with this AMD.

**Comment by netrunnereve** [comment]
Are you talking about FP16 on Pascal? Both my change and the DP4A code shouldn't affect how we use FP16 and I'm pretty sure that our Vulkan backend uses FP32 by default for your chip as FP16 is super slow.

I tried looking up the CUDA issue but I couldn't really find anything about it online. Then again I wouldn't be surprised if Nvidia converted all FP16 PTX instructions to FP32 assembly for the 1080ti since even with all that overhead it'll still run faster. I have no idea why they'll need to decrease the memory clock for that but I mean if it works for you... 🤷‍♀

**Comment by 0cc4m** [comment]
It's actually impossible to use fp16 for Vulkan compute on Pascal (except Tesla P100) with Nvidia, since the driver explicitely doesn't allow that.

**Comment by Danik-droid** [comment]
It's possible that my 1080ti is dying, in 3dmark it's unstable after about half an hour (memory read error)... That's probably the reason. I'm closing the topic, thanks for your help.
