### ISSUE TITLE
Eval bug: MMAP off causes offload output layer to fail

### ISSUE THREAD

**Issue by askmyteapot** [ggml-org/llama.cpp#18198]
### Name and Version

D:\llama.cpp(llvmB)>llama-cli --version
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 2 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3090, compute capability 8.6, VMM: yes
  Device 1: Tesla P40, compute capability 6.1, VMM: no
version: 7478 (0a271d82b)
built with Clang 20.1.8 for Windows x86_64

```D:\llama.cpp(llvmB)>llama-cli -m D:\text-generation-webui\models\magnum-v4-22b-Q6_K.gguf -ngl 99 -fa 1 -dev cuda0 --no-mmap
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 2 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3090, compute capability 8.6, VMM: yes
  Device 1: Tesla P40, compute capability 6.1, VMM: no

Loading model... \llama_model_load: error loading model: read error: An attempt was made to move the file pointer before the beginning of the file.

llama_model_load_from_file_impl: failed to load model                                                                                               \common_init_from_params: failed to load model 'D:\text-generation-webui\models\magnum-v4-22b-Q6_K.gguf'
srv    load_model: failed to load model, 'D:\text-generation-webui\models\magnum-v4-22b-Q6_K.gguf' 
```
```
D:\llama.cpp(llvmB)>llama-cli -m D:\text-generation-webui\models\magnum-v4-22b-Q6_K.gguf -ngl 99 -fa 1 -dev cuda0 --mmap
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 2 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3090, compute capability 8.6, VMM: yes
  Device 1: Tesla P40, compute capability 6.1, VMM: no

Loading model...


▄▄ ▄▄
██ ██
██ ██  ▀▀█▄ ███▄███▄  ▀▀█▄    ▄████ ████▄ ████▄
██ ██ ▄█▀██ ██ ██ ██ ▄█▀██    ██    ██ ██ ██ ██
██ ██ ▀█▄██ ██ ██ ██ ▀█▄██ ██ ▀████ ████▀ ████▀
                                    ██    ██
                                    ▀▀    ▀▀

build      : b7478-0a271d82b
model      : magnum-v4-22b-Q6_K.gguf
modalities : text
```

### Operating systems

Windows

### GGML backends

CUDA

### Hardware

Ryzen 5800x + 64GB DDR4 
Tesla P40 + RTX 3090

### Models

All models i tested, MoE, Dense, Granite 4 H Tiny

### Problem description & steps to reproduce

Mmap off causes the failure

### First Bad Commit

57c1e0564365b76a954304812cc90d3e60939bc7

### Relevant log output

```shell
above
```

**Comment by EverchangerL** [comment]
https://github.com/ggml-org/llama.cpp/pull/18204 should fix this, I hope

**Comment by JTischbein** [comment]
#18204 is merged, can you test again please?

**Comment by EverchangerL** [comment]
works fine on my end now, thanks

```
load_tensors: loading model tensors, this can take a while... (mmap = false)
load_tensors: offloading output layer to GPU
load_tensors: offloading 39 repeating layers to GPU
load_tensors: offloaded 41/41 layers to GPU
load_tensors:          CPU model buffer size =   275.00 MiB
load_tensors:        CUDA0 model buffer size =  5174.63 MiB
........................................................................................
common_init_result: added <|im_end|> logit bias = -inf
```

**Comment by h9j6k** [comment]
Hello, the problem still persists for me on intel dg1, model fails to load, bad address. At the moment I have to remove --no-mmap to use llama.cpp. I am not sure if the problem is related to async stuff. I filed an issue https://github.com/ggml-org/llama.cpp/issues/17302 last month and the workaround https://github.com/ggml-org/llama.cpp/commit/f1ffbba68e05aa180e350edebcdfbc0c77cebd4a basically was to disable async code altogether for intel dg1. So the fix https://github.com/ggml-org/llama.cpp/pull/18204 here in this issue may not work in my case.

**Comment by JTischbein** [comment]
Hi @h9j6k, the PR #18204 only fixes an integer overflow. Loading the model with `--no-mmap` uses asynchronous host-to-device copies to read concurrently from disk. 

Since [38eaf32](https://github.com/ggml-org/llama.cpp/commit/38eaf32af1da66caa930ce37e9dca1137c66f91c) is the first faulty commit, the problem should not lie in the asynchronous loading of the model, but in the Vulkan backend. Does the flag `--no-mmap` work with the workaround in [f1ffbba](https://github.com/ggml-org/llama.cpp/commit/f1ffbba68e05aa180e350edebcdfbc0c77cebd4a)?

**Comment by h9j6k** [comment]
> Does the flag --no-mmap work with the workaround in [f1ffbba](https://github.com/ggml-org/llama.cpp/commit/f1ffbba68e05aa180e350edebcdfbc0c77cebd4a)?

Thank you. Yes, https://github.com/ggml-org/llama.cpp/commit/f1ffbba68e05aa180e350edebcdfbc0c77cebd4a works with `--no-mmap` without problems. I only noticed the model loading failure this morning when I git pulled to the lastes commit build: 7502 (e1f15b454). I did a google search with `llama_model_load: error loading model: read error: Bad address` then I was pointed here. I thought this might be related.

**Comment by mixer3d** [comment]
just tried to run some model in a usual way, and i can confirm that bug with flag `--no-mmap` is still there: 

```
llama_model_load: error loading model: read error: Bad address
llama_model_load_from_file_impl: failed to load model
```

without the flag i can load model like before

Vulkan backend, build 7522

**Comment by JTischbein** [comment]
@mixer3d On which system and with which model do you see the error?

**Comment by mixer3d** [comment]
@JTischbein `ggml-org_gemma-3n-E4B-it-GGUF_gemma-3n-E4B-it-Q8_0.gguf` @ `Debian 6.17.8`, with vulkan backend

**Comment by JTischbein** [comment]
@mixer3d Do you also use the DG1?

**Comment by mixer3d** [comment]
@JTischbein I with intel iris integrated gpu:

```
ggml_vulkan: 0 = Intel(R) Iris(R) Xe Graphics (ADL GT2) (Intel open-source Mesa driver) | uma: 1 | fp16: 1 | bf16: 0 | warp size: 32 | shared memory: 65536 | int dot: 1 | matrix cores: none
```

**Comment by JTischbein** [comment]
@mixer3d Could you please test the code from PR #18166? Thank you

I will try to get a reproducer and debug this issue

**Comment by mixer3d** [comment]
Hi @JTischbein  I wanted to confirm that with the code from #18166 i can run model with `--no-mmap` flag like before. Thank you for fix.

```bash
$ ./llama-server --version
ggml_vulkan: Found 1 Vulkan devices:
ggml_vulkan: 0 = Intel(R) Iris(R) Xe Graphics (ADL GT2) (Intel open-source Mesa driver) | uma: 1 | fp16: 1 | bf16: 0 | warp size: 32 | shared memory: 65536 | int dot: 1 | matrix cores: none
version: 7518 (4c15dc2c6)
built with GNU 14.2.0 for Linux x86_64
```

**Comment by JTischbein** [comment]
@mixer3d Great to hear! Thanks for testing
